#!/bin/bash
#
# Start a throwaway Zotero instance for developing/testing this plugin.
#
# - Separate profile and data directory under tools/.test (never touches your
#   real Zotero library).
# - The plugin and the development bridge (tools/dev-bridge) are installed
#   unpacked from this source tree, so edits only need a restart.
# - Zotero's debug output goes to tools/.test/zotero.log.
# - The local HTTP server listens on $ZML_TEST_PORT (default 23129) so it does
#   not clash with a normally running Zotero (23119).
#
# Usage:
#   tools/test-profile.sh            start (or restart) the test instance
#   tools/test-profile.sh --reset    wipe the profile + data first, then start
#   tools/test-profile.sh --stop     stop the test instance
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TEST_DIR="${ZML_TEST_DIR:-$ROOT/tools/.test}"
PROFILE="$TEST_DIR/profile"
DATA="$TEST_DIR/data"
LOG="$TEST_DIR/zotero.log"
PORT="${ZML_TEST_PORT:-23129}"
ZOTERO_BIN="${ZOTERO_BIN:-/Applications/Zotero.app/Contents/MacOS/zotero}"
PLUGIN_ID="zotero-multiple-libraries@local.zotero.plugins"
BRIDGE_ID="zml-dev-bridge@local.zotero.plugins"

stop_instance() {
	# Only the instance running on *this* profile
	pkill -f -- "-profile $PROFILE " 2>/dev/null || true
	for _ in $(seq 1 20); do
		pgrep -f -- "-profile $PROFILE " >/dev/null 2>&1 || return 0
		sleep 0.5
	done
	pkill -9 -f -- "-profile $PROFILE " 2>/dev/null || true
}

case "${1:-}" in
	--stop)
		stop_instance
		echo "stopped"
		exit 0
		;;
	--reset)
		stop_instance
		# Only the Zotero profile and data (tools/.test also hosts the WebDAV test server)
		rm -rf "$PROFILE" "$DATA" "$LOG"
		;;
	"")
		stop_instance
		;;
	*)
		echo "unknown option $1" >&2
		exit 1
		;;
esac

if [ ! -x "$ZOTERO_BIN" ]; then
	echo "Zotero binary not found at $ZOTERO_BIN (set ZOTERO_BIN)" >&2
	exit 1
fi

mkdir -p "$PROFILE/extensions" "$DATA"

# Unpacked installs: a text file named after the plugin ID containing its path
printf '%s/\n' "$ROOT" > "$PROFILE/extensions/$PLUGIN_ID"
printf '%s/tools/dev-bridge/\n' "$ROOT" > "$PROFILE/extensions/$BRIDGE_ID"
# Make the add-on manager rescan the extensions directory
rm -f "$PROFILE/extensions.json" "$PROFILE/addonStartup.json.lz4"

cat > "$PROFILE/user.js" <<EOF
// Generated by tools/test-profile.sh
user_pref("extensions.zotero.httpServer.port", $PORT);
user_pref("extensions.zotero.httpServer.enabled", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.firstRunGuidance", false);
user_pref("extensions.zotero.sync.autoSync", false);
user_pref("extensions.zotero.automaticScraperUpdates", false);
user_pref("extensions.zotero.debug.log", true);
user_pref("extensions.zotero.debug.store", false);
user_pref("extensions.zotero.debug.level", 5);
user_pref("extensions.zotero.debug.time", true);
user_pref("app.update.enabled", false);
user_pref("app.update.auto", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.autoDisableScopes", 0);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
EOF

echo "profile: $PROFILE"
echo "data:    $DATA"
echo "log:     $LOG"
"$ZOTERO_BIN" -profile "$PROFILE" -datadir "$DATA" -no-remote -ZoteroDebugText -purgecaches > "$LOG" 2>&1 &
echo "pid:     $!"

# Wait for the HTTP server (and thus Zotero's initialization) to come up
for _ in $(seq 1 90); do
	if curl -s -o /dev/null "http://127.0.0.1:$PORT/connector/ping"; then
		echo "ready on port $PORT"
		exit 0
	fi
	sleep 1
done
echo "timed out waiting for Zotero; see $LOG" >&2
exit 1
